"""Export the thermo_optic LUT as CSV and as a Markdown table.

Run from math-engines/:  python tools/make_thermo_lut.py
writes engines/thermo_optic/thermo_optic_lut.csv and engines/thermo_optic/LUT.md (checked current by the tests).
"""
from __future__ import annotations

import csv
import io
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from engines.thermo_optic import engine as to  # noqa: E402

CSV_OUT = ROOT / "engines" / "thermo_optic" / "thermo_optic_lut.csv"
MD_OUT = ROOT / "engines" / "thermo_optic" / "LUT.md"
FIELDS = ["material", "name", "n_1550", "dn_dT", "dn_dT_min", "dn_dT_max", "k", "k_min", "k_max", "rho", "cp",
          "diffusivity", "alpha_L", "Eg", "beta_tpa", "n2", "confidence", "source"]


def _fmt(v, scale=1.0, digits=3):
    if v is None:
        return "–"
    return f"{v / scale:.{digits}g}"


def render_csv() -> str:
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=FIELDS, lineterminator="\n")
    w.writeheader()
    for r in to.lut_rows():
        w.writerow({k: ("" if r[k] is None else r[k]) for k in FIELDS})
    return buf.getvalue()


def render_md() -> str:
    head = ("# Thermo-optic LUT\n\nGenerated by `tools/make_thermo_lut.py` from `engines/thermo_optic/engine.py`; do not edit by hand. "
            "Room temperature (about 300 K), 1550 nm. n from the `materials` Sellmeier fits where one exists. "
            "Ranges in brackets; confidence: high = textbook value, medium = one or two consistent measurements, "
            "low = order-of-magnitude design value, measure the film. – = not tabulated.\n\n")
    cols = ("| material | n | dn/dT (1e-5/K) | k (W/m/K) | ρ (kg/m³) | c_p (J/kg/K) | D (mm²/s) | α_L (ppm/K) | E_g (eV) "
            "| β_TPA (cm/GW) | n₂ (1e-20 m²/W) | confidence |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n")
    lines = []
    for r in to.lut_rows():
        lines.append(
            f"| `{r['material']}` {r['name']} | {r['n_1550']:.4f} "
            f"| {_fmt(r['dn_dT'], 1e-5)} [{_fmt(r['dn_dT_min'], 1e-5)}, {_fmt(r['dn_dT_max'], 1e-5)}] "
            f"| {_fmt(r['k'])} [{_fmt(r['k_min'])}, {_fmt(r['k_max'])}] | {r['rho']:.0f} | {r['cp']:.0f} "
            f"| {_fmt(r['diffusivity'], 1e-6)} | {_fmt(r['alpha_L'], 1e-6)} | {_fmt(r['Eg'])} "
            f"| {_fmt(r['beta_tpa'], 1e-11)} | {_fmt(r['n2'], 1e-20)} | {r['confidence']} |")
    src = "\n\n## Sources\n\n" + "\n".join(f"- `{r['material']}`: {r['source']}" for r in to.lut_rows()) + "\n"
    return head + cols + "\n".join(lines) + src


if __name__ == "__main__":
    CSV_OUT.write_text(render_csv(), encoding="utf-8")
    MD_OUT.write_text(render_md(), encoding="utf-8")
    print(f"wrote {CSV_OUT.relative_to(ROOT)}, {MD_OUT.relative_to(ROOT)}", file=sys.stderr)
