"""Build <applet>-standalone.html: an artifact page wrapped as a complete HTML document.

The artifact host adds <!doctype html>, <head> (charset, viewport) and a small reset when it publishes a page;
this script adds the same so the file opens directly in a browser, offline.
Run from the repository root:  python tools/build_standalone.py [applet.html ...]   (default: all applets below)
"""
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APPLETS = {
    "cmpc-ray-tracer.html": ("CMPC Ray Tracer", "billiard_cell, ray_phase, bragg_grating (stack_R_oblique, TrenchDBR) and cell_mirror engines"),
    "fringe-washout.html": ("Fringe Washout Planner", "fringe_averaging engine"),
}


def build(name="cmpc-ray-tracer.html") -> str:
    title, engines = APPLETS[name]
    src = (ROOT / name).read_text(encoding="utf-8")
    try:
        rev = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], text=True, cwd=ROOT).strip()
    except (OSError, subprocess.CalledProcessError):
        rev = "unknown"
    title_end = src.index("</title>") + len("</title>")
    rest = src[title_end:]
    style_end = rest.index("</style>") + len("</style>")
    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<!--
  {title}, standalone single-file build (generated by tools/build_standalone.py; edit {name}).
  Source: github.com/mikkojhuttunen/misc-applets, {name} at commit {rev}.
  Physics: inline JS port (between the engine:begin / engine:end markers) of the misc-applets math-engines
  {engines}, checked there against the Python reference by math-engines/tools/check_js_ports.mjs.
  No build step and no server needed: open the file in a browser. Google Fonts are optional (system fonts offline).
  Heavy analyses run in Web Workers created from the inline engine (blob URLs).
-->
{src[:title_end]}
<style>
:root {{ color-scheme: light; }}
body {{ margin: 0; }}
img {{ max-width: 100%; }}
[hidden] {{ display: none !important; }}
</style>
{rest[:style_end]}
</head>
<body>
{rest[style_end:].strip()}
</body>
</html>
'''


if __name__ == "__main__":
    for name in sys.argv[1:] or list(APPLETS):
        out = ROOT / name.replace(".html", "-standalone.html")
        out.write_text(build(name), encoding="utf-8")
        print(f"wrote {out.name}")
